// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

contract wordSelector {

    address public owner;
    string[261] private words = [
        "there",
        "their",
        "about",
        "would",
        "these",
        "other",
        "words",
        "could",
        "write",
        "first",
        "water",
        "after",
        "where",
        "right",
        "think",
        "three",
        "years",
        "place",
        "sound",
        "great",
        "again",
        "still",
        "every",
        "small",
        "found",
        "those",
        "never",
        "under",
        "might",
        "while",
        "house",
        "world",
        "below",
        "asked",
        "going",
        "large",
        "until",
        "along",
        "shall",
        "being",
        "often",
        "earth",
        "began",
        "since",
        "study",
        "night",
        "light",
        "above",
        "paper",
        "parts",
        "young",
        "story",
        "point",
        "times",
        "heard",
        "whole",
        "white",
        "given",
        "means",
        "music",
        "miles",
        "thing",
        "today",
        "later",
        "using",
        "money",
        "lines",
        "order",
        "group",
        "among",
        "learn",
        "known",
        "space",
        "table",
        "early",
        "trees",
        "short",
        "hands",
        "state",
        "black",
        "shown",
        "stood",
        "front",
        "voice",
        "kinds",
        "makes",
        "comes",
        "close",
        "power",
        "lived",
        "vowel",
        "taken",
        "built",
        "heart",
        "ready",
        "quite",
        "class",
        "bring",
        "round",
        "horse",
        "shows",
        "piece",
        "green",
        "stand",
        "birds",
        "start",
        "river",
        "tried",
        "least",
        "field",
        "whose",
        "girls",
        "leave",
        "added",
        "color",
        "third",
        "hours",
        "moved",
        "plant",
        "doing",
        "names",
        "forms",
        "heavy",
        "ideas",
        "cried",
        "check",
        "floor",
        "begin",
        "woman",
        "alone",
        "plane",
        "spell",
        "watch",
        "carry",
        "wrote",
        "clear",
        "named",
        "books",
        "child",
        "glass",
        "human",
        "takes",
        "party",
        "build",
        "seems",
        "blood",
        "sides",
        "seven",
        "mouth",
        "solve",
        "north",
        "value",
        "death",
        "maybe",
        "happy",
        "tells",
        "gives",
        "looks",
        "shape",
        "lives",
        "steps",
        "areas",
        "sense",
        "speak",
        "force",
        "ocean",
        "speed",
        "women",
        "metal",
        "south",
        "grass",
        "scale",
        "cells",
        "lower",
        "sleep",
        "wrong",
        "pages",
        "ships",
        "needs",
        "rocks",
        "eight",
        "major",
        "level",
        "total",
        "ahead",
        "reach",
        "stars",
        "store",
        "sight",
        "terms",
        "catch",
        "works",
        "board",
        "cover",
        "songs",
        "equal",
        "stone",
        "waves",
        "guess",
        "dance",
        "spoke",
        "break",
        "cause",
        "radio",
        "weeks",
        "lands",
        "basic",
        "liked",
        "trade",
        "fresh",
        "final",
        "fight",
        "meant",
        "drive",
        "spent",
        "local",
        "waxes",
        "knows",
        "train",
        "bread",
        "homes",
        "teeth",
        "coast",
        "thick",
        "brown",
        "clean",
        "quiet",
        "sugar",
        "facts",
        "steel",
        "forth",
        "rules",
        "notes",
        "units",
        "peace",
        "month",
        "verbs",
        "seeds",
        "helps",
        "sharp",
        "visit",
        "woods",
        "chief",
        "walls",
        "cross",
        "wings",
        "grown",
        "cases",
        "foods",
        "crops",
        "fruit",
        "stick",
        "wants",
        "stage",
        "sheep",
        "nouns",
        "plain",
        "drink",
        "bones",
        "apart",
        "turns"
    ];

    constructor(address ownerAddress) {
        owner = ownerAddress;
    }


    function getWord (uint256 index) view  private returns (string memory) {
        require(index < 261, "word index is out of range");
        return words[index];
    }

    modifier onlyOwner() {
        require(msg.sender == owner, 'you are not the owner of this contract');
        _;
    }

    modifier newWordHas5Characters(string memory s) {
        bytes memory wordBytes = bytes(s);
        require(wordBytes.length == 5, "word must be 5 characters long");
        _;
    }

    function replaceWord (uint256 _index, string memory _newWord) onlyOwner newWordHas5Characters(_newWord) public {
        require(_index < 261, "word index is out of range");
        words[_index] = _newWord;
    }

    function generateRandomInt () private pure returns (uint256){
        return 200;
    }

    function pickWordAtRandom () public  view returns (string memory){
        uint256 index = generateRandomInt();
        return getWord(index);
    }
}